'use strict';

module.exports = {
  wait : {
    short: 1000,
    long: 6000,
    splashscreen: 1000,
  },

  timeout : {
    app: 36000,
  },

  username: "bob",
  message1: "First message.",
  message2: "Second message.",
  update: "Updated with some more text!",

  deviceIdentity: "AppiumDeviceIdentity",
  cardId1: "postcard-0-"+this.deviceIdentity,
  cardText1: "Try some long words: Floccinaucinihilipilification, Supercalifragilisticexpialidocious",
  cardAuthor: "Appium",
  cardImage: "/9j/4AAQSkZJRgABAQEASABIAAD/2wCEABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2MBERISGBUYLxoaL2NCOEJjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY//AABEIAIAAgAMBEQACEQEDEQH/xACKAAEAAwEBAAAAAAAAAAAAAAAAAQIEAwUQAAIBAgQBCAcIAwAAAAAAAAABAgMRBBIhMQUTFDVBUWF0sjNicXKCkbEGFSJGVIGhwkJzwQEBAQEBAQEAAAAAAAAAAAAAAAEDAgQFEQEAAgECBAYDAQAAAAAAAAAAAQIRAxIxM0FREyFCYXGBMkPwRP/aAAwDAQACEQMRAD8AobPigAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASbAnLpe6sEyhpr2BQAAAtyU1SVXK8jllUu8LicZVCAAABalSnWqRp04uU5bJdYWIm04ghTnUU3CLahHNK3UgREzwVCAExS3lsBMleTV9e8JCf88nwlPdCVpb69iIIklvHa4IdcHRWIxdGjJtKc1FtCWlK7rRDlUjkqSj2NoOZjE4bJdCU/ES8qJ1azyvtiKxAAADbwbpXD+9/xktwbaHMhxw2IVCNdON+VpuG+2qd/wCBMOKW2593ArgAs07LqVt2ESoxm7KaT9bRMDesDV5LnGTVRt1WzbXv2W1uMtPDnbux5MLjGm9Zpy9XW37hnKqi7PrVt0DLdwfF4injKFCFWSpSqK8ep3OZh6NG9otFYnyVr8UxvKVI85nlu1YuIS2tfMxl2oV1h+CKahGVTnElByV1H8K1sTHm6rbbpZ92f72x36iVuyysXbDjxtTunGqNfCUcWoRhOcpQqKKsm1Z3t7GI7LfFqxd1xWJqcOqLC4Vqnkis80lmlJq71/ckRnzl1e86c7auP3tj/wBVMu2HHjandu/NS9/+pPS2/f8A3Zi4d6LG+HfmRZZaXC3wxFYgFnJ2XWrbMIlShDXJmfrPRAegsdV5Hm91dxzWsrX3tbssMNPEnbt6MDlCo9YZX6r0YZqqTs7aK2yBho4X0nhv9i+pJ4NdL84cK3p6nvP6lc24y1S6Ep+Il5UTq0nlfbEVi2z6EpeIl5UTq2nlR8nGelK/tX0QrwNfmSxFYva/NS99eU59L1/v/uzFw70WN8O/Miyy0uFvhiKxAJi1tLYJKZNKTeW77wQm75TP8QOmERacr5bPfQCJNbR2uCHbA1Y0cdQqT0jGom33XJPBppzttEyY6hPD4qpGcWrybi+qS6mhBqVmtpy7S6Ep+Il5UOrueV9sRWLbPoSl4iXlROraeVHyni8XLFc5ir0q0YyjLq2V17biDWjNt3SWWhQqYiqqdOLbf8LtZWdazacQ9Z6fav4/6nPpen/R/dmLh3osb4d+ZFllpcLfDEViAACbQE5/w2srbhMIbb9gUAAaKPEMXQgoU681BbReqXzJiGldW9YxEuLqzdJUnJ5FLNbv7SuN04wqEWdWbpKlmeRSzKPeFzOMOuHxmJwycaNaUIvdJ6fImIl1XUtXhK1biGLrQcKlebg94rRP5DELOre0YmXPnNbnHOOUfK3vm6y4c77bt3VSFWdNTUJNKccsu9BImY4KhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//9k=",

  cardId2: "postcard-1-"+this.deviceIdentity,
  cardText2: "Lopadotemachoselachogaleokranioleipsanodrimhypotrimmatosilphioparaomelitokatakechymenokichlepikossyphophattoperisteralektryonoptekephalliokigklopeleiolagoiosiraiobaphetraganopterygon",

  contactId: "addressbook-"+this.deviceIdentity,
  contactUsername: "Appium.saved",
  contactDeviceId: this.deviceIdentity,
};
